### ISSUE TITLE
--dist-url key is mentioned to be optional, but seem mandatory when running

### ISSUE THREAD

**Issue by yitzhtal** [jfrog/release-bundle-generators#3]
<img width="677" alt="Screen Shot 2020-06-14 at 15 52 52" src="https://user-images.githubusercontent.com/15890481/84594069-5e429b80-ae58-11ea-9b7a-34a08ecc9a87.png">
<img width="1227" alt="Screen Shot 2020-06-14 at 15 52 42" src="https://user-images.githubusercontent.com/15890481/84594072-60a4f580-ae58-11ea-9af5-78647a8cc046.png">

**Comment by DarthFennec** [comment]
To clarify, if you use `release-bundle-generator config` to configure a distribution url, you don't have to pass `--dist-url`, and that's why it's optional.
